### ISSUE TITLE
Замечания по чрезмерно длинному коду

### ISSUE THREAD

**Issue by sergey-shambir** [nikolai996/MainGame#5]
- в Bullet::update можно переписать, аналогично в Enemy::update

``` cpp
position.x += speed * (temp.x - boost.x);
position.y += speed * (temp.y - boost.y);
/////
position += (temp - boost) * speed;
```
- в Player::update для всех case можно переписать

``` cpp
boost.x = speed;
boost.y = 0;
/////
boost = {speed, 0};
```
- в Enemy.cpp съехало форматирование
- в конструкторе Bullet переустанавливаются некоторые поля, которые уже были установлены в конструкторе базового класса Entity

**Comment by H4817** [comment]
исправил
